<!--
<div id="sidebar">
            <div class="alphaWrapper">
            <a href="#" target="_blank" wrc_done="true"><img src="<?php echo $this->baseUrl() ?>/public/img/Merch-2.png" alt="For the geek who has everything-Wolfram gear" title="For the geek who has everything-Wolfram gear"></a>
            </div>
</div>
-->
<h1>Who We are?</h1>

<p>Design Source Labs has started its journey with a vision to instigate a platform for research that is needed and appropriate for our country. Initially DSLabs has started with embedded system developing, electronic circuit imagesing and developing other IT related projects and promoting advance design solutions. </p>

<p>We respect the fact that every project is unique and the needs of the project vary over its history. Thus our assistance also needs to be flexible enough to adapt with the needs of the project. Our offering is very simple − a versatile group of professionals from whom you can draw the right skills at the right time to solve the problems at hand at that particular point of the project.</p>

    