<!--
<div id="sidebar">
            <div class="alphaWrapper">
            <a href="#" target="_blank" wrc_done="true"><img src="<?php echo $this->baseUrl() ?>/public/img/Merch-2.png" alt="For the geek who has everything-Wolfram gear" title="For the geek who has everything-Wolfram gear"></a>
            </div>
</div>
-->
<p>
<h1>Welcome to Design Source LAB Ltd.</h1>
<img src="<?php echo $this->baseUrl() ?>/public/img/piston_cylender.jpg">

<p>
<img src="<?php echo $this->baseUrl() ?>/public/img/prototype.jpg">
Whether you're modeling gas or liquid piping systems, perfecting your system design, studying your system's transient behavior or need fluid property data,solidworks has the engineering software tools to meet your needs. — Call :01712108076
</p>
<p>
<img src="<?php echo $this->baseUrl() ?>/public/img/bridge.jpg">

Leadership is the willingness to take responsibility for all of it. At the end of the day, you are responsible for a business…its customers, its employees, vendors, etc. A leader can not be blind via delegation, but must accept responsibility    
</p>